# permissions for end users to edit elastichorovodjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastichorovodjob-editor-role
rules:
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - elastichorovodjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - elastichorovodjobs/status
  verbs:
  - get
