# permissions for end users to view elastichorovodjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastichorovodjob-viewer-role
rules:
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - elastichorovodjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - elastichorovodjobs/status
  verbs:
  - get
