# permissions for end users to view horovodjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horovodjob-viewer-role
rules:
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - horovodjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - horovodjobs/status
  verbs:
  - get
