# permissions for end users to edit horovodjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horovodjob-editor-role
rules:
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - horovodjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.centauruscloud.io
  resources:
  - horovodjobs/status
  verbs:
  - get
