apiVersion: v1
kind: Service
metadata:
  name: torchelastic-etcd-service
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --data-dir
    - /var/lib/etcd
    - --enable-v2
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://0.0.0.0:2379
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:latest
    name: etcd
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
    resources: 
      requests: 
        memory: '64Mi'
        cpu: '1000m'
      limits: 
        memory: '128Mi'
        cpu: '1500m'
  restartPolicy: Always