apiVersion: ai.centauruscloud.io/v1alpha1
kind: UnifiedJob
metadata:
  name: basesample
jobType: BaseJob
spec:
  jobSpec:
    image: hxhp/elastic-horovod-demo:1.0
    pythonCommand:
      - sleep 600
  replicaSpec:
    minReplicas: 2
    maxReplicas: 5
